[[icon-links]]
url = "https://reddit.com"
icon = "reddit"

[[columns.common]]
url = "https://my.wpengine.com"
label = "WP Engine"

[[columns.work]]
url = "https://projects.drivendigital.us"
label = "OpenProjects"

[[columns.work]]
url = "https://trello.com"
label = "Trello"




